#spring.application.name=e-learning
spring:
    application:
      name : e-learning

    data:
        mongodb:
          uri: mongodb://localhost:27017/e-learning

    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/identity

server:
  tomcat:
    relaxed-query-chars: >
      |,[,],{,}
  forward-headers-strategy: framework
  port: 8550
stream:
  image: http://localhost:8080/image/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://sarandy:1234@mongodb-docker:27017/
      authentication-database: admin
      database: e-learning

